describe('Pruebas', () =>{

    /*it('Prueba 1', () => {
        cy.visit('http://demo.vetagile.com/login')
        cy.wait(1000)
        cy.get('[name ="email"]').type('ludk17@gmail.com')
        cy.get('[name ="password"]').type('123456qwerty')
        cy.wait(1000)
        cy.get('[class="btn btn-primary"]').click()
        cy.wait(1000)
        cy.get ('[class="navbar-avatar"]').click()
        cy.get('[class="fa fa-btn fa-h-square"]').click()
        cy.wait(1000)
        cy.get('[class="btn btn-primary pull-right"]').click()
        cy.get('[id="form.name"]').type('Caballos2')
        cy.get('[id="form.description"]').type('Caballos de Indiana Jones')
        //cy.get('[class="btn btn-primary"]').should("have.text","Guardar").click({force:true})
        //cy.get('[class="btn btn-primary"]').last().should("have.text","Guardar").click({force:true})
        //cy.get('div.btn btn-primary').click()
        cy.get('div.modal-footer').find('[class="btn btn-primary"]').click()
        //cy.get('[id="form.description"]').type("{enter}", {force: true})
        cy.wait(1000)
        cy.get('[close="updateItemTable(data)"]').first().click()
        cy.get('[id="form.description"]').type('Caballos de Indiana Jones, ahora del Janero Solitario')
        cy.get('div.modal-footer').find('[class="btn btn-primary"]').click()
        cy.wait(2000)
        cy.get('[close="removeItemFromTable(data)"]').first().click()
        cy.get('[class="btn btn-white"]').contains("Eliminar").click()
        })*/

        it('Prueba 2', () => {
            cy.visit('http://demo.vetagile.com/login')
            cy.wait(1000)
            cy.get('[name ="email"]').type('ludk17@gmail.com')
            cy.get('[name ="password"]').type('123456qwerty')
            cy.wait(1000)
            cy.get('[class="btn btn-primary"]').click()
            cy.wait(1000)
            cy.get ('[class="navbar-avatar"]').click()
            cy.get('[class="fa fa-btn fa-h-square"]').click()
            cy.get('ul.nav li').contains("Antiparasitarios y Antipulgas").click()
            cy.wait(1000)
            cy.get('[class="btn btn-primary pull-right"]').contains("Nuevo Medicamento").click()
            cy.get('[id="form.name"]').type('AstralPuro')
            cy.get('[id="form.default_price"]').type('121')
            cy.get('[id="form.description"]').type('Producto de Primera Calidad')
            cy.get('div.modal-footer').find('[class="btn btn-primary"]').click()
            cy.wait(1000)
            cy.get('[close="updateItemTable(data)"]').first().click()
            cy.get('[id="form.description"]').type('Producto de Primera Calidad Compralo Ahora')
            cy.get('div.modal-footer').find('[class="btn btn-primary"]').click()
            cy.wait(2000)
            cy.get('[close="removeItemFromTable(data)"]').first().click()
            cy.get('[class="btn btn-white"]').contains("Eliminar").click()
            })



})